### ISSUE TITLE
Move OQ_Toolkit to addons/ ?

### ISSUE THREAD

**Issue by Wavesonics** [NeoSpark314/godot_oculus_quest_toolkit#1]
This would make it fit a bit better if it's going to be put on the asset library at some point.

**Comment by NeoSpark314** [comment]
I have not yet looked into the requirements for the asset library. Do all things need to be in the addons subfolder? That would make everything one hierarchy-level deeper to access for drag and drop but that should not be a big problem.

**Comment by NeoSpark314** [comment]
I had a look into how other projects are handling this. A common solution seems to be to have a separate git repo for the godot asset store release. I think this is a good solution as it clearly separates the development version (that contains a lot of unwanted files) from the requirements for the asset store. We just need to make sure that the full toolkit works independent of the position in the directory hierarchy.
What do you think?

**Comment by Wavesonics** [comment]
Ya that would be a nice solution.

It's certainly nice when adding something from the asset library to just be able to check the addon's dir and leave the rest out. Other wise they can stomp on your files on accident if there is a name collision. And it just keeps your code separate from library code.

**Comment by Wavesonics** [comment]
Btw, awesome project, I'm going to be using it as a base for some Quest based projects soon!

**Comment by NeoSpark314** [comment]
Thanks for the answer and also thanks for the feedback :-); I'll keep the issue open until I have created the separate asset repo. cu

**Comment by NeoSpark314** [comment]
I decided for now to not create a separate addon repository as the toolkit is still in an early state and rapidly changing. Moving it would introduce overhead in testing and increasing the risk of introducing more bugs that go unnoticed due to the different structure.
Nevertheless I pushed it to the asset repo: https://godotengine.org/asset-library/asset/506
and people using it need to be careful to select only the things they actually need or require. From my experience using the asset download this is an acceptable overhead compared to the risk in releasing code that what not tested with the new folder structure as much as the current code.
